apiVersion: v1
kind: ConfigMap
metadata:
  name: app-{{APP_ID}}-config
  namespace: app-{{APP_ID}}
data:
  # Настройки приложения
  DEBUG: "False"
  ALLOWED_HOSTS: "app-{{APP_ID}}.yourdomain.com,localhost"
  
  # Nginx конфигурация (если нужно переопределить)
  # nginx.conf: |
  #   server {
  #     listen 8080;
  #     server_name _;
  #     ...
  #   }