apiVersion: v1
kind: Secret
metadata:
  name: app-{{APP_ID}}-secret
  namespace: app-{{APP_ID}}
type: Opaque
stringData:
  # Django admin credentials
  django-superuser-username: "admin"
  django-superuser-password: "admin"  # В production используйте генератор паролей!
  django-superuser-email: "admin@mail.ru"
  
  # Django secret key (опционально, если используете)
  # django-secret-key: "your-secret-key-here"
  
  # Database credentials (если нужно)
  # database-url: "postgresql://user:pass@host:5432/dbname"