apiVersion: v1
kind: Service
metadata:
  name: app-{{APP_ID}}-svc
  namespace: app-{{APP_ID}}
  labels:
    app: app-{{APP_ID}}
spec:
  type: ClusterIP
  selector:
    app: app-{{APP_ID}}
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP